# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b356c1b18c95f9c0fa5cac7be5bb6b0239fe912f478faef172e1e713c2fd8abf9fe8afaee024fc9eb53d241b808521de3be5760963926e170f88b28fe7b48089

test:
  secret_key_base: 5f07505ff7d3e2df7d7be12613e91541d0fc85025d56c662338e21eb5a40a595d68d8bf01a4635ee468e76b24ec70aa239e14b0f831003dafa8658b7214b03e5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
